name: Laravel Dusk Tests

on: [push, pull_request]

jobs:
  dusk-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Altere para a versão PHP que está usando

      - name: Install Dependencies
        run: |
          cp .env.example .env
          composer install
          php artisan key:generate

      - name: Install Chromedriver
        run: php artisan dusk:chrome-driver --detect

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Laravel Dusk Tests
        env:
          APP_URL: http://localhost
        run: php artisan dusk
